baseURL = ''
languageCode = 'en-us'
title = 'Blipz Tech Radar 2025'

buildFuture = true
disableLanguages = ["nl"]
disqusShortname = ""
pagination.pagerSize = "6"
summaryLength = "10"
theme = "tech-radar"
[Languages.en]
contentDir = "content/english"
copyright = "Copyright &copy; 2025 by [kokkelaar](https://kokkelaar.nl)"
home = "Home"
languageCode = "nl-NL"
languageName = "En"
weight = 2
[Languages.nl]
contentDir = "content/dutch"
copyright = "Copyright &copy; 2025 by [kokkelaar](https://kokkelaar.nl)"
home = "Home"
languageCode = "nl-NL"
languageName = "Nl"
weight = 1




[[module.mounts]]
lang = "nl"
source = "content/dutch"
target = "content"
[[module.mounts]]
lang = "en"
source = "content/english"
target = "content"
[[module.mounts]]
source = "static"
target = "static"
[[module.mounts]]
source = "layouts"
target = "layouts"
[[module.mounts]]
source = "data"
target = "data"
[[module.mounts]]
source = "assets"
target = "assets"
[[module.mounts]]
source = "static"
target = "assets/static"
[[module.mounts]]
source = "i18n"
target = "i18n"
[[module.mounts]]
source = "archetypes"
target = "archetypes"
[params]
address = "Tractieweg 41 , 3534 AP Utrecht"
author = ""
contact_form_action = ""
description = ""
email = ""
google_analitycs_id = "G-3PG6NYRP8M"
logo = "images/logo.png"
mobile = ""
top_header = false
[params.map]
enable = false
map_latitude = "52.105107"
map_longitude = "5.079772"
map_marker = "images/marker.png"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/animate/animate.css"
[[params.plugins.css]]
link = "plugins/venobox/venobox.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/owl.carousel/assets/owl.carousel.min.css"
[[params.plugins.css]]
link = "plugins/owl.carousel/assets/owl.theme.default.min.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/venobox/venobox.min.js"
[[params.plugins.js]]
link = "plugins/filterizr/jquery.filterizr.min.js"
[[params.plugins.js]]
link = "plugins/owl.carousel/owl.carousel.min.js"
[[params.plugins.js]]
link = "plugins/scrollreveal/scrollreveal.min.js"
[[params.plugins.js]]
link = "plugins/rellax/rellax.min.js"
[[params.plugins.js]]
link = "plugins/tech-radar/d3.min.js"
[[params.plugins.js]]
link = "plugins/tech-radar/random.js"
[[params.plugins.js]]
link = "plugins/tech-radar/tech-radar.js"
[params.preloader]
enable = false
preloader = "images/preloader.gif"
[params.subscription]
enable = false
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074"
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074"

[[params.social]]
icon = "ti-linkedin"
link = "https://www.linkedin.com/company/dataworkz/"
title = "linkedin"
