baseURL = ''
languageCode = 'en-us'
title = 'Blipz Tech Radar 2025'

buildFuture = true
disableLanguages = ["nl"]
disqusShortname = ""
pagination.pagerSize = "6"
summaryLength = "10"
theme = "tech-radar"

